version: "3"
services:
    frontend:
        build: instantelegram/.
        image: igfrontend
        ports:
            - '80:80'
        depends_on:
            - "backend"
    backend:
        build: instantelegramback/.
        image: igbackend
        ports:
            - '5000:5000'
        environment:
            DATABASE_URL: postgresql://ig_app_user:v6sk3jsl@db/ig_app_prod
            SECRET_KEY: ${SECRET_KEY}
        networks:
            ignetwork:
        depends_on:
            - "db"
        command: ["./wait-for", "db:5432", "-t", "60", "--", "./start.sh"]
    db:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: ig_app_user
            POSTGRES_PASSWORD: v6sk3jsl
            POSTGRES_DB: ig_app_prod
        volumes:
            - postgres-db:/var/lib/postgresql/data
        networks:
            ignetwork:

networks:
    ignetwork:

volumes:
    postgres-db:
